import './globals.css'
import type { Metadata } from 'next'
import LocalFont from 'next/font/local'
import { Inter,Roboto } from 'next/font/google'
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })
const roboto = Roboto({
  subsets:['latin'],
  weight:['500']
})
const localf = LocalFont({
  src:'../public/Font/poppins-regular-webfont.woff2'
})
export const metadata: Metadata = {
  title: 'cose nanat',
  description: 'Generated by create next app',
  
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
     
      <body className={localf.className}>
        {children}</body>
    </html>
  )
}
